### ISSUE TITLE
Definition of Essential 

### ISSUE THREAD

**Issue by GreggVan** [w3c/wcag21#580] opened 2017-11-14 16:00 UTC
I like your definition of essential.   It seems quite good.

However - you use the word "essential" in several places in the document -- and all your examples are just for one use.   You should include "examples"  that correspond to the different uses of the word in different places.    (and link them all to the same definition)

**Comment by steverep** [comment] 2017-11-15 04:23
Duplicate of #372

**Comment by awkawk** [comment] 2017-11-17 15:01
Agree that this is a duplicate of #372, but as it also has implementation advice to re-review for Understanding document work, I'm marking with the appropriate label (implementation follow-up) and closing.

**Closed by awkawk** 2017-11-17 15:01 UTC
Labels: Implementation Follow-up
