### ISSUE TITLE
Success Criterion 1.4.13 Adapting Text -- COMMENT  3

### ISSUE THREAD

**Issue by GreggVan** [w3c/wcag21#349] opened 2017-09-01 03:57 UTC
Comment 3

One more thing.

 This provision requires that authors not interfere with user agents that allow style properties to be adapted. This would require the author to know exactly how every single different type of user agent might support styles. That is, they would be required to not interfere with something that they had no idea existed or how it worked

SOLUTION
We might approach this in one of two ways
1)  you might restrict this to just CSS

2)  you might restrict this to common browsers or the most common browsers or something like that.

 If you're really just worried about CSS you might however just restricted to that.

**Comment by DavidMacDonald** [comment] 2017-09-05 19:22
Doesn't WCAG only require each SC to work on one affordable stack, not ALL stacks?

**Comment by allanj-uaag** [comment] 2017-09-06 18:19
lvtf

**Comment by lauracarlson** [comment] 2017-09-12 20:08
I would be in favor of restricting this SC to CSS.  Most HTML pages passed the Adapting Text SC.  Check the [Results of Bookmarklet Tests for Issue 78](https://www.w3.org/WAI/GL/wiki/Results_of_Bookmarklet_Tests_for_Issue_78). 

Testing PDFs present issues. As noted in the [Results of VIP-PDF Reader Tests for Issue 78](https://www.w3.org/WAI/GL/wiki/Results_of_VIP-PDF_Reader_Tests_for_Issue_78), VIP-PDF Reader has no adjustment for spacing underneath paragraphs.

So that metric can't be tested. And it can be difficult to set a window size of 1280px by 768px for testing in VIP-PDF Reader. @mraccess77  [previously asked about measuring viewport size](https://lists.w3.org/Archives/Public/public-low-vision-a11y-tf/2017Jul/0112.html
) for PDF readers for our tests. I used [Free Ruler](http://www.pascal.com/software/freeruler/) for the first 7. Check the VIP-PDF Reader Results tab in [the spreadsheet](https://docs.google.com/spreadsheets/d/1LRsAtLReBL6LnbvJQ4biQ1ER1fKbh8MDWnHqbsW7B1o/edit#gid=1060062606). I included the VIP PDF-Reader's chrome but we may want to change that to just the content area.

Unless someone has a good idea for a PDF testing procedure for this SC (paging @awkawk ), one option would be, to restrict it to CSS. 

Thoughts?

**Comment by mraccess77** [comment] 2017-09-12 20:10
I'd rather keep the SC than lose it over lack of support in other formats.  So if it comes down to it I'm fine with restricting this to CSS.

**Comment by steverep** [comment] 2017-09-12 20:23
> Testing PDFs presents issues. As noted in the Results of VIP-PDF Reader Tests for Issue 78, VIP-PDF Reader has no adjustment for spacing underneath paragraphs.

Is that the only reason for wanting to restrict to CSS?  If so, I would much rather drop the paragraph spacing bullet as unnecessary.  An HTML document also has no clear way to adjust this; the bookmarklet is making assumptions.

**Comment by lauracarlson** [comment] 2017-09-12 20:35
Hi @steverep

> Is that the only reason for wanting to restrict to CSS? If so, I would much rather drop the paragraph spacing bullet as unnecessary. An HTML document also has no clear way to adjust this; the bookmarklet is making assumptions.

@kerstinp previously raised 2 additional concerns [internationalization](https://github.com/w3c/wcag21/issues/78#issuecomment-323662527) and  [how to decide if a failure is a user agent issue or an technology issue](https://github.com/w3c/wcag21/issues/78#issuecomment-323961512).

**Comment by steverep** [comment] 2017-09-14 17:13
Getting back to @GreggVan's original assertion:

> This provision requires that authors not interfere with user agents that allow style properties to be adapted.

The cause and effect relationship is wrong here: the web technology is providing the allowance here, not the user agent.  HTML/CSS/JavaScript are of course included here because they are passed as text to the user agent and thus can be modified.  Flash and Silverlight are not included because their plugins would need to include an API that allows specifically for changing these properties.

> This would require the author to know exactly how every single different type of user agent might support styles. That is, they would be required to not interfere with something that they had no idea existed or how it worked

I don't think this makes sense once the above is realized.  The author only need be familiar with the technologies they are using and whether or not support exists for adapting styles once content is transferred to the user agent, which will all be covered in Understanding like other technology specific capabilities and techniques.

Moreover, how all possible user agents render a technology is not something WCAG expects authors to know with regard to any criterion.  Rather, they only need know that the technology can combine with a user agent and meet the definition of accessibility supported.

**Comment by awkawk** [comment] 2017-11-30 03:27
As @steverep stated, the Web technology is providing the allowance for this SC, not the user agent. HTML/CSS/JavaScript is included because they are passed as text to the user agent and thus can be modified.

The author only need be familiar with the technologies they are using and whether or not support exists for adapting styles once content is transferred to the user agent, which will all be covered in the Understanding document like other technology specific capabilities and techniques. Moreover, how all possible user agents render a technology is not something WCAG expects authors to know with regard to any criterion. Rather, they only need know that the technology can combine with a user agent and meet the definition of accessibility supported.

**Closed by awkawk** 2017-11-30 03:27 UTC
Labels: LVTF, Member Comment, ~comment-adapting-text
