### ISSUE TITLE
Plain language (Enhanced)

### ISSUE THREAD

**Issue by lseeman** [w3c/wcag21#41] opened 2016-11-27 12:03 UTC
# Current versions of SC and Definitions
- [SC for viewing](https://rawgit.com/w3c/wcag21/plain-language-enhanced_ISSUE-41/guidelines/sc/21/plain-language-enhanced.html) | [SC for editing](https://github.com/w3c/wcag21/blob/plain-language-enhanced_ISSUE-41/guidelines/sc/21/plain-language-enhanced.html)
-  [Core vocabulary definition for viewing](https://rawgit.com/w3c/wcag21/plain-language-minimum_ISSUE-30/guidelines/terms/21/core-vocabulary.html) | [Core vocabulary definition for editing](https://github.com/w3c/wcag21/blob/plain-language-minimum_ISSUE-30/guidelines/terms/21/core-vocabulary.html)
- [Word frequency list for the identified context definition for viewing](https://rawgit.com/w3c/wcag21/plain-language-minimum_ISSUE-30/guidelines/terms/21/identified-context.html) | [Word frequency list for the identified context definition for editing](https://github.com/w3c/wcag21/blob/plain-language-minimum_ISSUE-30/guidelines/terms/21/identified-context.html)
- [Important information definition for viewing](https://rawgit.com/w3c/wcag21/plain-language-minimum_ISSUE-30/guidelines/terms/21/important-information.html) | [important information definition for editing](https://github.com/w3c/wcag21/blob/plain-language-minimum_ISSUE-30/guidelines/terms/21/important-information.html)
- [SC in full draft guideline](https://rawgit.com/w3c/wcag21/plain-language-enhanced_ISSUE-41/guidelines/#plain-language-(minimum-error-messages,-instructions,-labels,-navigational-elements))
Note these terms are also used for #42 so be sure not to wind up with colliding definitions.
----------

Not the discussion for AA is at issue #30 
Full proposal is at [Plain language AA](https://rawgit.com/w3c/coga/master/extension/plain-language-aa.html)
Note we have been asked: 

- not to worry about formatting at this point.
- Testability is to show that the proposed success criteria is potentially testable rather than be intended as rigorous test

More information and explanations are available on request.

**Comment by DavidMacDonald** [comment] 2016-12-02 08:26
Seems to be a duplicate of #30

**Comment by lseeman** [comment] 2016-12-02 08:55
No it is not. Again different scopes.All the bestLisa SeemanLinkedIn, Twitter---- On Fri, 02 Dec 2016 10:26:06 +0200  David MacDonald<notifications@github.com> wrote ----Seems to be a duplicate of #30  —You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by joshueoconnor** [comment] 2017-01-13 11:37
Assigned to Jim Smith (@jim-work) https://www.w3.org/WAI/GL/wiki/SC_Managers_Phase1

**Comment by joshueoconnor** [comment] 2017-02-04 17:36
@jim-work Is there a PR ready to go for this?

**Comment by jspellman** [comment] 2017-02-13 02:48
This is difficult to measure and to implement. I recommend looking at using reading level. It isn't perfect, but it addresses most of the user needs identified, especially when paired with existing Technique G153. Reading level has international support, it has automated tests, and it has a variety of formulas (Flesh-Kincaid is the oldest and best known, there are many others.)

Proposed revision:
**Understandable Instructions**:  Headings, error messages and instructions for completing tasks do not require reading ability greater than lower secondary education level.  (AA)  

[link to WCAG’s definition of lower secondary level from UNESCO standard]  
Techniques should include [G153](https://www.w3.org/TR/WCAG20-TECHS/G153.html) Making text Easier to Read.

**Comment by lseeman** [comment] 2017-02-15 07:44
Hi Jeane. This has been fully addressed both on the coga thread and in the A version. As you know the revision does not to the task we need as reading levels make it easier to read but NOT easier to understand. Each statement is fully testable and although the accessibility tools do not currently address this issue, tools are easy to make and already exist in other industries.

**Comment by cstrobbe** [comment] 2017-02-23 12:44
This proposal has many of the same issues as https://github.com/w3c/wcag21/issues/30. Should I repeat them here? 

With regard to the wording of the first sentence: this should be worded as a characteristic of the content instead of an instruction to web content authors, e.g.: 

**Plain language (enhanced)**: Headings, error messages and important information use language that fulfils the following criteria: (...)

I left out terms like "plain", "clear" and "simple" since these terms are vague (in the absence of definitions) and the actual criteria are expressed in the bullet points. However, if the plan is to have several SCs about plain language, the SC can also be worded as "Headings, error messages and important information use plan language", where "plain language" links to a normative definition that contains the bullet points.

**Comment by eadraffan** [comment] 2017-08-03 11:57
I have read some of the comments on the review about the lack of examples of core vocabularies.  Those using Augmentative and Alternative forms of communication depend on core vocabularies in their own language and there have been several versions of these types of vocabularies developed in many languages.  These lists are often made up of function words that can be used as alternatives to complex words that might link important /specialist words which are usually nouns in all languages.  These lists have been collected by professionals working in the field and it should be possible to collate samples.

**Closed** 2017-08-24 16:17 UTC
Labels: COGA, Defer to Silver, Ready for WG Review
