### ISSUE TITLE
2.4.11 Character Key Shortcuts - one key or more?

### ISSUE THREAD

**Issue by alastc** [w3c/wcag21#769] opened 2018-02-12 17:05 UTC
Comment from a collegue who just through the new SC: 
"I'm left a bit unsure whether this criterion applies to singular keyboard shortcuts or multiple keyboard shortcuts, such as hijacking Shift + P, or just hijacking P."

My memory of the issue is that it should be single-key characters, without modifiers. If so, then I think we are missing something:

> "If a keyboard shortcut is implemented in content using only letter (including upper- and lower-case letters), punctuation, number, or symbol characters, then at least one of the following is true:"

(And keyboard shortcut is "one or more keys")

I suggest an editorial update to:
> "If a keyboard shortcut is implemented in content using only **a** letter (including upper- and lower-case letters), punctuation, number, or symbol character, then ..."

(Adding "a letter", and removing the plural from symbol character**s**).

**Comment by awkawk** [comment] 2018-02-20 17:42
Thank you for commenting. For more information about how the AG WG will process this issue, see the following:
- [Issue Processing](https://www.w3.org/WAI/WCAG21/comments/#issueprocessing) - How the WG will discuss the issue
- [Issue Resolution](https://www.w3.org/WAI/WCAG21/comments/#issueresolution) - Identifying and responding to the official WG response
- [Issue Notification](https://www.w3.org/WAI/WCAG21/comments/#issuenotification) - How to limit notifications from GitHub

**Comment by mbgower** [comment] 2018-02-20 18:32
(Proposed response)
We agree that clarity has been lost in the revision. When the parenthetical material was added "(including upper- and lower-case letters)" it made the previous phrase less clear, which in its prior form read:

> If a keyboard shortcut is implemented in content using only letter, punctuation, number, or symbol characters, then at least one of the following is true:

So, to clarify, this Success Criterion was intended to apply to both single- and multiple-character keyboard shortcuts where no modifier key in included. Although the most common implementation being addressed involves the use of a single character, the working group felt the language should also include shortcuts that involve multiple-character shortcuts.

---

That said, @KimPatch, have you encountered situations where a multiple-character shortcut has been implemented? If this is a significant outlier, it may be advisable to update the language to reflect the much more common scenario, as suggested by @alastc .

**Comment by alastc** [comment] 2018-02-20 21:40
Ah, if it is intended to include multiple (un-modified) keys then leave the SC text alone (but clarify in understanding).

I haven't come across that situation, would you be pressing J, then A (for example) as one 'keyboard shortcut'? Or both at the same time? 

Presumably it is the sequence that would impact voice input, rather than multiple keys at the same time?

**Comment by KimPatch** [comment] 2018-02-23 18:21
Yes @alastc, it is intended to include multiple unmodified keys, but this is theoretical – I haven't come across it. Greg Lowney suggested it, and he's right. If someone implemented j, then a as one keyboard shortcut it could mess up speech users. At the same time, the more letters you have, the smaller chance a stray word will hit the right combination in a row. So single keys are a huge problem, two or three-letter combinations are a smaller problem (theoretically). And long letter combinations are unique enough to be handled very well, which is why one of the suggested techniques is to allow users to modify using a string of up to 25 letter keys.

**Comment by alastc** [comment] 2018-02-24 07:44
Thanks @KimPatch, in which case I’d suggest saying that it is single or multiple strings somewhere in the first 3 paragraphs of the intent.

The second parragraph refers to single-key shortcuts, so perhaps there?

**Comment by KimPatch** [comment] 2018-02-27 01:11
@alastc @mbgower 
Sounds good – done.

**Closed** 2018-02-27 09:43 UTC
