### ISSUE TITLE
Comment on Issue #10 User Interface Components Contrast

### ISSUE THREAD

**Issue by DavidMacDonald** [w3c/wcag21#384] opened 2017-09-19 17:08 UTC
the Editor's note says 

> Under consideration: simplify this Success Criterion by setting the minimum color contrast requirement to 3:1 and removing any need for measuring thickness.

I agree with this and think it should happen in the next draft because of:
* Testing implications of measuring the size of things
* IU Components easier to discern than text which requires 4.5:1

**Comment by awkawk** [comment] 2017-11-09 23:56
Closing as a duplicate of 489

**Closed by awkawk** 2017-11-09 23:56 UTC
Labels: LVTF, Member Comment, ~comment-UI-component-contrast
