### ISSUE TITLE
Success Criterion 1.3.4 Identify Common Purpose       [Trace]

### ISSUE THREAD

**Issue by GreggVan** [w3c/wcag21#602] opened 2017-12-06 16:57 UTC
> Success Criterion 1.3.4 Identify Common Purpose§
> (Level AA) [New]
> In content implemented using markup languages, for each user interface component that serves a purpose identified in the Common Purposes for User Interface Components section, that purpose can be programmatically determined.

much better 
but a bit ambiguous that you need to user the term in the list 

suggest that you add "USING THE LISTED NAME"  to the end. 

In content implemented using markup languages, for each user interface component that serves a purpose identified in the Common Purposes for User Interface Components section, that purpose can be programmatically determined USING THE LISTED NAME.

**Comment by awkawk** [comment] 2017-12-19 22:04
WG Response: Thank you for your comment. The list of purposes is explicitly not requiring that the author use the specific text to identify a purpose, so adding the requirement to use the listed name is different than what we intended. For example, the "Table of Contents" purpose may be referenced using a different term depending on whether the author is incorporating metadata from one schema or another - one schema might use "toc" and another might use "tableOfContents" but as long as they are aligned with the purpose expressed in the list (and as long as there is accessibility support) either would be sufficient.

**Comment by GreggVan** [comment] 2017-12-21 03:49
thank you but this does not respond to my comment 

you can leave this closed though since I elaborated on it in issue 635

**Comment by awkawk** [comment] 2018-01-10 02:00
closing as duplicate of 635.

**Closed by awkawk** 2018-01-10 02:00 UTC
Labels: Dec WD Comment, Member Comment, ~comment-identify-common-purpose
